### ISSUE TITLE
Validate StructureMaps based on connection to Questionnaires

### ISSUE THREAD

**Issue by pld** [onaio/fhir-tooling#199]
Extend validation tooling and expand CI to:

1. Parse the Composition to create a map from Questionnaires to the StructureMaps
2. For each (Questionnaire, StructureMap) pair
    1. Generate a QuestionnnaireResponse for the Questionnaire
    2. Run the StructureMap against the QuestionnaireResponse and output a list of additional [Resources]
        - Fail any StructureMap fails to run
    1. For each Resource in the output list of [Resources]
        1. Validate it is valid FHIR with valid references
            - Fail if any resource is invalid or has invalid references
3. Pass

**Comment by pld** [comment]
Some what related issue, https://github.com/onaio/fhir-tooling/issues/6

**Comment by pld** [comment]
Some what related issue, https://github.com/opensrp/fhircore/issues/3113

**Comment by f-odhiambo** [comment]
NB. We need some form of template validation that will help validate gaps in missing reference that cause malformed resources e.g.

1. Encounter.subject  = `Patient/$patient_id`  = valid
3. Encounter,subject  = `$patient_id`  is not valid 
5. Encounter,subject  = `Patient/`   is not valid

This should apply to other Resource that reference each other

**Comment by pld** [comment]
Good call, yep we probably need something like a linter for FHIR, or a very rudimentary version of that

**Comment by dubdabasoduba** [comment]
@Wambere @f-odhiambo I am looking at this validation in 2 stages

### Stage 1
- Here we validate the schema i.e. is the generated resource a valid FHIR resource? 
- This will check for all the required FHIR properties and their syntax making sure the resources are valid. 
- This uses the HAPI validator lib which is already added as a dependency on the efsity based on [this](https://github.com/onaio/fhir-tooling/tree/main/efsity#validating-fhir-resources) function
- This step addresses the comments by @f-odhiambo  [here](https://github.com/onaio/fhir-tooling/issues/199#issuecomment-2165939791) 

### Stage 2 
- Here we go a little deeper in the reference validation.  
- We know the references are correctly structured if they pass stage 1. 
- This stage checks if the referenced resources actually exist. 
- We might need 2 approaches for this
   1. For some cases checking the referenced resources in the generated bundle will suffice since all the subject resources are in the bundle.  Examples of such situations are when testing the SM and QR generated during client/entity registration.
   2. For other cases we might want to provide a way to give the validator the subject resources referenced but not found on the current extracted bundle by:-
       - Adding them in a folder somewhere
       - Adding the server credentials of where the subject resource might be found.  The validator would then access the server in search of the subject resource. 
- This stage also addresses the comments by @pld [here](https://github.com/onaio/fhir-tooling/issues/199#issue-2349501065) 

cc: @pld

**Comment by pld** [comment]
Sounds good, for stage 2 we would not want to access a server, we need to have this test work without assuming anything exists that the test writer cannot control.

There's a potential Stage 3 where we write the extracted resources first, or a subset of them, like should create this resources with these keys filled... hmm actually instead of writing the extracted resource a Profile might be want we want , then we validate that the extracted resources matches the target (or the profile). And later we build tooling to generate the structuremap from the Q and the target/profile

@Wambere let's focus on Stage 1 for now, get that into CI, then we can revisit the approach for Stage 2 and how it fits into our priorities.

**Comment by pld** [comment]
marking as blocked by #15

**Comment by Wambere** [comment]
Breaking this down to actionable tasks

- [ ] Create a new command in efsity to validate structureMaps
           - Call it `validateStructureMap`
           - The composition resource should be one of the required inputs
           - Ideally also include a folder path with questionnaires and structureMaps
- [ ] Create a function that parses the composition and maps Questionnaires to StructureMaps
           - Write tests for the function
- [ ] For each Questionnaire use the `generateResponse` command to generate QuestionnaireResponses
           - Use the `validateFhir` command to validate the generated QuestionnaireResponses
- [ ] Write function that runs the StructureMap against the generated and validated QuestionnaireResponses to get the expected resources
           - Write tests for the function
           - If successfully generates resources, use the `validateFhir` command to validate the output resources. Pass if all generated resources are valid, and fail if any of them are invalid
           - If fails to generate resources, fail. The structureMap is invalid
- [ ] Update documentation
- [ ] Integrate into the CI workflow

cc @pld @ndegwamartin

**Comment by Wambere** [comment]
@pld @dubdabasoduba @f-odhiambo @ndegwamartin 

We are trying to map the Questionnaires and StructureMaps in the composition file and we're trying to figure out if it's possible for us to all agree on the same format to naming these resources. For example can we enforce that the `title` should always match? Or the `title` and the  `identifier.value` should always match (replacing spaces with `-` or something like that) 

For example:

_composition_config.json_
```json
[
  {
    "title": "Questionnaires",
    "mode": "working",
    "section": [
      {
        "title": "Add Family Member",
        "focus": {
          "reference": "Questionnaire/ccaedb32-0e23-4a29-8df1-bde75bf4a183",
          "identifier": {
            "value": "add-family-member"
          }
        },
        "mode": "working"
      }
    ]
  },
  {
    "title": "StructureMaps",
    "mode": "working",
    "section": [
      {
        "title": "Add Family Member",
        "focus": {
          "reference": "StructureMap/eb7e8cbb-4cef-4d62-9e4d-7d4243b68c80",
          "identifier": {
            "value": "add-family-member"
          }
        },
        "mode": "working"
      }
    ]
  }
]
```

**Comment by dubdabasoduba** [comment]
@Wambere @sharon2719 I am okay with the suggested naming approach.  Can we add it to the validation?  So validation fails if the naming is not adhered to.
