### ISSUE TITLE
Set Up Test Framework - efsity

### ISSUE THREAD

**Issue by lincmba** [onaio/fhir-tooling#73]
Superceded https://github.com/onaio/fhir-tooling/issues/20
FHIRCore Tooling currently lacks a proper testing framework. This is crucial for ensuring the stability, reliability, and quality of our tool, especially as we continue to develop and enhance its features. This will allow us to write and execute tests to validate the functionality of the tool and catch potential issues early in the development process.

**Tasks**

- [x] Identify the right testing frameworks for each of the modules in fhircore tooling (_`cleaner`_,  _`efsity`_ , _`importer`_ , _`uploader`_)
- [x] Integrate the relevant testing framework to each of the project: JUnit for Java modules, Pytest for python modules
- [x]  Write a set of initial test cases.
- [ ]  Set up CircleCI to automatically run tests on code changes.
- [ ] Ensure all modules/directories mentioned above are covered in the CI tests
- [ ] Add documentation on testing
- [ ] Update the Engineer Checklist on the Pull Request Template to include CI passing
